### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [SergeevnaEkaterina/Minesweeper#1]
Пока проект явно не доделан, но есть несколько замечаний.
1. `makeImages` у Вас сейчас только замедляет работу, потому что загружает все картинки для каждой открываемой клетки вместо одной, как это было раньше. Эту функцию достаточно вызвать один раз, где-нибудь в `start`, тогда это действительно будет иметь смысл. Кстати, `images` лучше сделать массивом, ведь ключи у Вас - это последовательные числа от 0 до 6.
1. Можно поспорить на этот счёт, но я бы сказал, что рекурсивное открытие всех соседей пустой клетки - это задача модели. Поэтому я бы предложил перенести это рекурсивное открытие из `Game.reveal` в `Board.openCell`.

**Comment by maximpetrov** [comment]
1. Поля классов должны быть `private`. Вы придерживаетесь этого правила для `Element`, но не для `Board`.
1. Мелочь, но непонятно, зачем Вам 2 объекта `Random` в `createBoard()`, если можно и один использовать.
1. Не совсем понятно, почему `openElement` у Вас package-private, а `reveal` - `public`, хотя сейчас именно `reveal` является служебным методом и должен быть `private`.
1. Добавление ссылок на `images` и `honeyComb` в `Board` - нарушение MVC. `Board` - класс модели, так что он не должен ничего знать об интерфейсе и тем более перерисовывать его. В идеале стоит воспользоваться механизмом событий для отслеживания открытия клеток в интерфейсе, но меня устроит и полная перепроверка поля после нажатия на клетку.
1. Проект выглядит недоделанным: нет никаких сообщений о конце игры, а победа вообще не проверяется, только поражение.

**Comment by maximpetrov** [comment]
1. Всё-таки сделайте `openElement` `public`, а `reveal` - `private`. Использование в тестах не оправдание, логичнее там как раз использовать `openElement`.
1. Перенос методов перерисовки и картинок в `Graphics` ничего принципиально не поменял. Вы всё равно из модели ссылаетесь на объекты интерфейса (тот же `Graphics`). Повторюсь, если не хотите реализовывать механизм событий (это не так уж и сложно), то просто перепроверяйте все ячейки из `Game` после клика.
1. `Message` - тоже часть интерфейса, `Board` не должен с ним взаимодействовать. Проще всего (и правильнее) вместо `end` сделать `enum` со статусом (игра/победа/поражение), а сообщение отображать по результатам проверки этого статуса из `Game` опять же после клика.
1. Диалоговое окно у Вас, кстати, не диалоговое. Вы зачем-то специально выставляете `Modality.NONE` вместо `Modality.APPLICATION_MODAL`.
1. Проверка условия победы у Вас неправильная. Я так понял, что Вы пытаетесь считать выставленные флаги. Во-первых, условие, при котором уменьшается `bombCount` у Вас очень странное. Вы уменьшаете его, когда **снимается** флаг с клетки **без мины**. То есть можно просто покликать достаточное число раз правой кнопкой почти в любую клетку и выиграть. Боле того, в случае реальной победы (все флаги на местах) ничего не произойдёт. Во-вторых, определять победу по числу флагов неправильно, Вы же сами у меня уточняли, что флаги носят скорее вспомогательную функцию. Если просто проверять число флагов, то победить можно просто выставив нужное число флагов в произвольных клетках. Если учитывать только флаги над минами, то можно просто заполнить всё поле флагами и победить. Если при этом проверять, что флагов ровно столько, сколько нужно, то всё равно это даёт возможность в спорных случаях победить перебором (когда вариантов осталось немного, но непонятно какой правильный) при этом не рискуя взорваться на мине. Единственный правильный способ победить - открыть все клетки кроме тех, где мины, можно даже флагами их не отмечать.
1. У Вас нельзя кликнуть по ячейке с флагом, но она может быть автоматически открыта из-за соседней пустой. В таком случае нужно убирать флаг и открывать ячейку.

**Comment by maximpetrov** [comment]
1. Ссылка на `Game` из `Board` - такое же нарушение MVC. К тому же Вы даже не ссылаетесь на существующий объект `Game`, а создаёте новый, в котором размеры по умолчанию (12 на 12 и 10 мин), так что подсчёт получается неверным для других размеров и победа не срабатывает или срабатывает раньше времени. На самом деле, непонятно, почему Вы решили сделать вычисление количества свободных клеток в `Game`. Во-первых, это вполне задача модели и интерфейсу следует просто брать это значение из неё, если нужно. Во-вторых, у Вас это ему и не нужно, Вы используете `getFree` только для инициализации `rest`.
1. https://github.com/SergeevnaEkaterina/Minesweeper/blob/aaf7607a967b10297fec748fcf2baeab5ef46dd4/src/sample/Game.java#L151-L175 Вместо `if` лучше использовать `switch`.
1. Обновление поля следует вынести в отдельный метод, чтобы два раза вызвать вместо копирования.
1. Сейчас заметил, что `bombsClose` в `Element` у Вас типа `long`. Почему не `int`? Думаете может быть больше 2 млрд мин рядом с клеткой? К тому же Вам типы приводить приходится кое-где.

**Comment by SergeevnaEkaterina** [comment]
https://github.com/SergeevnaEkaterina/Minesweeper

  
>Среда, 17 июня 2020, 22:29 +03:00 от Maxim Petrov <notifications@github.com>:
> 
> 
>*  Ссылка на Game из Board - такое же нарушение MVC. К тому же Вы даже не ссылаетесь на существующий объект Game, а создаёте новый, в котором размеры по умолчанию (12 на 12 и 10 мин), так что подсчёт получается неверным для других размеров и победа не срабатывает или срабатывает раньше времени. На самом деле, непонятно, почему Вы решили сделать вычисление количества свободных клеток в Game. Во-первых, это вполне задача модели и интерфейсу следует просто брать это значение из неё, если нужно. Во-вторых, у Вас это ему и не нужно, Вы используете getFree только для инициализации rest.
>*  https://github.com/SergeevnaEkaterina/Minesweeper/blob/aaf7607a967b10297fec748fcf2baeab5ef46dd4/src/sample/Game.java#L151-L175 Вместо if лучше использовать switch.
>*  Обновление поля следует вынести в отдельный метод, чтобы два раза вызвать вместо копирования.
>*  Сейчас заметил, что bombsClose в Element у Вас типа long. Почему не int? Думаете может быть больше 2 млрд мин рядом с клеткой? К тому же Вам типы приводить приходится кое-где.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Екатерина Герасина
